language: rust
cache: cargo
rust:
  - nightly
  - stable
  - beta
os:
  - linux

addons:
  apt:
    packages:
    - libmnl-dev

script:
  - cd mnl/
  - cargo build --verbose --no-default-features
  - cargo test --verbose --no-default-features
  - cd ../
  - if [ "${TRAVIS_RUST_VERSION}" = "nightly" ]; then
      rustup component add rustfmt-preview;
      rustfmt --version;
      cargo fmt -- --check --unstable-features;
    else
      echo "Not checking formatting on this build";
    fi


notifications:
  email:
    on_success: never
    on_failure: never
