required_version = "0.3.8"

# Activation of features, almost objectively better ;)
reorder_imports = true
reorder_imported_names = true
reorder_imports_in_group = true
use_try_shorthand = true
condense_wildcard_suffixes = true
normalize_comments = true
wrap_comments = true

# Heavily subjective style choices
comment_width = 100
blank_lines_upper_bound = 2
