// automatically generated by rust-bindgen

use libc::{self, c_int, nlattr, nlmsghdr, pid_t, socklen_t, FILE};

pub const MNL_SOCKET_AUTOPID: c_int = 0;
pub const MNL_ALIGNTO: c_int = 4;
pub const MNL_CB_ERROR: c_int = -1;
pub const MNL_CB_STOP: c_int = 0;
pub const MNL_CB_OK: c_int = 1;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mnl_socket {
    _unused: [u8; 0],
}
extern "C" {
    pub fn mnl_socket_open(bus: libc::c_int) -> *mut mnl_socket;
}
extern "C" {
    #[cfg(feature = "mnl-1-0-4")]
    pub fn mnl_socket_open2(bus: libc::c_int, flags: libc::c_int) -> *mut mnl_socket;
}
extern "C" {
    #[cfg(feature = "mnl-1-0-4")]
    pub fn mnl_socket_fdopen(fd: libc::c_int) -> *mut mnl_socket;
}
extern "C" {
    pub fn mnl_socket_bind(nl: *mut mnl_socket, groups: libc::c_uint, pid: pid_t) -> libc::c_int;
}
extern "C" {
    pub fn mnl_socket_close(nl: *mut mnl_socket) -> libc::c_int;
}
extern "C" {
    pub fn mnl_socket_get_fd(nl: *const mnl_socket) -> libc::c_int;
}
extern "C" {
    pub fn mnl_socket_get_portid(nl: *const mnl_socket) -> libc::c_uint;
}
extern "C" {
    pub fn mnl_socket_sendto(nl: *const mnl_socket, req: *const libc::c_void, siz: usize) -> isize;
}
extern "C" {
    pub fn mnl_socket_recvfrom(nl: *const mnl_socket, buf: *mut libc::c_void, siz: usize) -> isize;
}
extern "C" {
    pub fn mnl_socket_setsockopt(
        nl: *const mnl_socket,
        type_: libc::c_int,
        buf: *mut libc::c_void,
        len: socklen_t,
    ) -> libc::c_int;
}
extern "C" {
    pub fn mnl_socket_getsockopt(
        nl: *const mnl_socket,
        type_: libc::c_int,
        buf: *mut libc::c_void,
        len: *mut socklen_t,
    ) -> libc::c_int;
}
extern "C" {
    pub fn mnl_nlmsg_size(len: usize) -> usize;
}
extern "C" {
    pub fn mnl_nlmsg_get_payload_len(nlh: *const nlmsghdr) -> usize;
}
extern "C" {
    pub fn mnl_nlmsg_put_header(buf: *mut libc::c_void) -> *mut nlmsghdr;
}
extern "C" {
    pub fn mnl_nlmsg_put_extra_header(nlh: *mut nlmsghdr, size: usize) -> *mut libc::c_void;
}
extern "C" {
    pub fn mnl_nlmsg_ok(nlh: *const nlmsghdr, len: libc::c_int) -> bool;
}
extern "C" {
    pub fn mnl_nlmsg_next(nlh: *const nlmsghdr, len: *mut libc::c_int) -> *mut nlmsghdr;
}
extern "C" {
    pub fn mnl_nlmsg_seq_ok(nlh: *const nlmsghdr, seq: libc::c_uint) -> bool;
}
extern "C" {
    pub fn mnl_nlmsg_portid_ok(nlh: *const nlmsghdr, portid: libc::c_uint) -> bool;
}
extern "C" {
    pub fn mnl_nlmsg_get_payload(nlh: *const nlmsghdr) -> *mut libc::c_void;
}
extern "C" {
    pub fn mnl_nlmsg_get_payload_offset(nlh: *const nlmsghdr, offset: usize) -> *mut libc::c_void;
}
extern "C" {
    pub fn mnl_nlmsg_get_payload_tail(nlh: *const nlmsghdr) -> *mut libc::c_void;
}
extern "C" {
    pub fn mnl_nlmsg_fprintf(
        fd: *mut FILE,
        data: *const libc::c_void,
        datalen: usize,
        extra_header_size: usize,
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mnl_nlmsg_batch {
    _unused: [u8; 0],
}
extern "C" {
    pub fn mnl_nlmsg_batch_start(buf: *mut libc::c_void, bufsiz: usize) -> *mut mnl_nlmsg_batch;
}
extern "C" {
    pub fn mnl_nlmsg_batch_next(b: *mut mnl_nlmsg_batch) -> bool;
}
extern "C" {
    pub fn mnl_nlmsg_batch_stop(b: *mut mnl_nlmsg_batch);
}
extern "C" {
    pub fn mnl_nlmsg_batch_size(b: *mut mnl_nlmsg_batch) -> usize;
}
extern "C" {
    pub fn mnl_nlmsg_batch_reset(b: *mut mnl_nlmsg_batch);
}
extern "C" {
    pub fn mnl_nlmsg_batch_head(b: *mut mnl_nlmsg_batch) -> *mut libc::c_void;
}
extern "C" {
    pub fn mnl_nlmsg_batch_current(b: *mut mnl_nlmsg_batch) -> *mut libc::c_void;
}
extern "C" {
    pub fn mnl_nlmsg_batch_is_empty(b: *mut mnl_nlmsg_batch) -> bool;
}
extern "C" {
    pub fn mnl_attr_get_type(attr: *const nlattr) -> u16;
}
extern "C" {
    pub fn mnl_attr_get_len(attr: *const nlattr) -> u16;
}
extern "C" {
    pub fn mnl_attr_get_payload_len(attr: *const nlattr) -> u16;
}
extern "C" {
    pub fn mnl_attr_get_payload(attr: *const nlattr) -> *mut libc::c_void;
}
extern "C" {
    pub fn mnl_attr_get_u8(attr: *const nlattr) -> u8;
}
extern "C" {
    pub fn mnl_attr_get_u16(attr: *const nlattr) -> u16;
}
extern "C" {
    pub fn mnl_attr_get_u32(attr: *const nlattr) -> u32;
}
extern "C" {
    pub fn mnl_attr_get_u64(attr: *const nlattr) -> u64;
}
extern "C" {
    pub fn mnl_attr_get_str(attr: *const nlattr) -> *const libc::c_char;
}
extern "C" {
    pub fn mnl_attr_put(nlh: *mut nlmsghdr, type_: u16, len: usize, data: *const libc::c_void);
}
extern "C" {
    pub fn mnl_attr_put_u8(nlh: *mut nlmsghdr, type_: u16, data: u8);
}
extern "C" {
    pub fn mnl_attr_put_u16(nlh: *mut nlmsghdr, type_: u16, data: u16);
}
extern "C" {
    pub fn mnl_attr_put_u32(nlh: *mut nlmsghdr, type_: u16, data: u32);
}
extern "C" {
    pub fn mnl_attr_put_u64(nlh: *mut nlmsghdr, type_: u16, data: u64);
}
extern "C" {
    pub fn mnl_attr_put_str(nlh: *mut nlmsghdr, type_: u16, data: *const libc::c_char);
}
extern "C" {
    pub fn mnl_attr_put_strz(nlh: *mut nlmsghdr, type_: u16, data: *const libc::c_char);
}
extern "C" {
    pub fn mnl_attr_put_check(
        nlh: *mut nlmsghdr,
        buflen: usize,
        type_: u16,
        len: usize,
        data: *const libc::c_void,
    ) -> bool;
}
extern "C" {
    pub fn mnl_attr_put_u8_check(nlh: *mut nlmsghdr, buflen: usize, type_: u16, data: u8) -> bool;
}
extern "C" {
    pub fn mnl_attr_put_u16_check(nlh: *mut nlmsghdr, buflen: usize, type_: u16, data: u16)
        -> bool;
}
extern "C" {
    pub fn mnl_attr_put_u32_check(nlh: *mut nlmsghdr, buflen: usize, type_: u16, data: u32)
        -> bool;
}
extern "C" {
    pub fn mnl_attr_put_u64_check(nlh: *mut nlmsghdr, buflen: usize, type_: u16, data: u64)
        -> bool;
}
extern "C" {
    pub fn mnl_attr_put_str_check(
        nlh: *mut nlmsghdr,
        buflen: usize,
        type_: u16,
        data: *const libc::c_char,
    ) -> bool;
}
extern "C" {
    pub fn mnl_attr_put_strz_check(
        nlh: *mut nlmsghdr,
        buflen: usize,
        type_: u16,
        data: *const libc::c_char,
    ) -> bool;
}
extern "C" {
    pub fn mnl_attr_nest_start(nlh: *mut nlmsghdr, type_: u16) -> *mut nlattr;
}
extern "C" {
    pub fn mnl_attr_nest_start_check(nlh: *mut nlmsghdr, buflen: usize, type_: u16) -> *mut nlattr;
}
extern "C" {
    pub fn mnl_attr_nest_end(nlh: *mut nlmsghdr, start: *mut nlattr);
}
extern "C" {
    pub fn mnl_attr_nest_cancel(nlh: *mut nlmsghdr, start: *mut nlattr);
}
extern "C" {
    pub fn mnl_attr_type_valid(attr: *const nlattr, maxtype: u16) -> libc::c_int;
}
pub const MNL_TYPE_UNSPEC: mnl_attr_data_type = 0;
pub const MNL_TYPE_U8: mnl_attr_data_type = 1;
pub const MNL_TYPE_U16: mnl_attr_data_type = 2;
pub const MNL_TYPE_U32: mnl_attr_data_type = 3;
pub const MNL_TYPE_U64: mnl_attr_data_type = 4;
pub const MNL_TYPE_STRING: mnl_attr_data_type = 5;
pub const MNL_TYPE_FLAG: mnl_attr_data_type = 6;
pub const MNL_TYPE_MSECS: mnl_attr_data_type = 7;
pub const MNL_TYPE_NESTED: mnl_attr_data_type = 8;
pub const MNL_TYPE_NESTED_COMPAT: mnl_attr_data_type = 9;
pub const MNL_TYPE_NUL_STRING: mnl_attr_data_type = 10;
pub const MNL_TYPE_BINARY: mnl_attr_data_type = 11;
pub const MNL_TYPE_MAX: mnl_attr_data_type = 12;
pub type mnl_attr_data_type = u32;
extern "C" {
    pub fn mnl_attr_validate(attr: *const nlattr, type_: mnl_attr_data_type) -> libc::c_int;
}
extern "C" {
    pub fn mnl_attr_validate2(
        attr: *const nlattr,
        type_: mnl_attr_data_type,
        len: usize,
    ) -> libc::c_int;
}
extern "C" {
    pub fn mnl_attr_ok(attr: *const nlattr, len: libc::c_int) -> bool;
}
extern "C" {
    pub fn mnl_attr_next(attr: *const nlattr) -> *mut nlattr;
}
pub type mnl_attr_cb_t = ::core::option::Option<
    unsafe extern "C" fn(attr: *const nlattr, data: *mut libc::c_void) -> libc::c_int,
>;
extern "C" {
    pub fn mnl_attr_parse(
        nlh: *const nlmsghdr,
        offset: libc::c_uint,
        cb: mnl_attr_cb_t,
        data: *mut libc::c_void,
    ) -> libc::c_int;
}
extern "C" {
    pub fn mnl_attr_parse_nested(
        attr: *const nlattr,
        cb: mnl_attr_cb_t,
        data: *mut libc::c_void,
    ) -> libc::c_int;
}
extern "C" {
    pub fn mnl_attr_parse_payload(
        payload: *const libc::c_void,
        payload_len: usize,
        cb: mnl_attr_cb_t,
        data: *mut libc::c_void,
    ) -> libc::c_int;
}
pub type mnl_cb_t = ::core::option::Option<
    unsafe extern "C" fn(nlh: *const nlmsghdr, data: *mut libc::c_void) -> libc::c_int,
>;
extern "C" {
    pub fn mnl_cb_run(
        buf: *const libc::c_void,
        numbytes: usize,
        seq: libc::c_uint,
        portid: libc::c_uint,
        cb_data: mnl_cb_t,
        data: *mut libc::c_void,
    ) -> libc::c_int;
}
extern "C" {
    pub fn mnl_cb_run2(
        buf: *const libc::c_void,
        numbytes: usize,
        seq: libc::c_uint,
        portid: libc::c_uint,
        cb_data: mnl_cb_t,
        data: *mut libc::c_void,
        cb_ctl_array: *mut mnl_cb_t,
        cb_ctl_array_len: libc::c_uint,
    ) -> libc::c_int;
}
